<option selected>Job Category</option>
<option value="Accounting/Finance">Accounting/Finance</option>
<option value="Administrative/Clerical">Administrative/Clerical</option>
<option value="Advertising/Marketing/Public Relations">Advertising/Marketing/Public Relations</option>
<option value="Agriculture/Forestry/Fishing">Agriculture/Forestry/Fishing</option>
<option value="Arts/Entertainment/Publishing">Arts/Entertainment/Publishing</option>
<option value="Automotive">Automotive</option>
<option value="Banking/Mortgage">Banking/Mortgage</option>
<option value="Biotech/Pharmaceutical">Biotech/Pharmaceutical</option>
<option value="Construction/Facilities">Construction/Facilities</option>
<option value="Customer Service/Call Center">Customer Service/Call Center</option>
<option value="Education/Training">Education/Training</option>
<option value="Engineering">Engineering</option>
<option value="Government/Military">Government/Military</option>
<option value="Healthcare">Healthcare</option>
<option value="Hospitality/Travel">Hospitality/Travel</option>
<option value="Human Resources">Human Resources</option>
<option value="Information Technology">Information Technology</option>
<option value="Insurance">Insurance</option>
<option value="Legal">Legal</option>
<option value="Manufacturing/Production">Manufacturing/Production</option>
<option value="Nonprofit/Volunteer">Nonprofit/Volunteer</option>
<option value="Real Estate">Real Estate</option>
<option value="Retail/Wholesale">Retail/Wholesale</option>
<option value="Sales">Sales</option>
<option value="Science/Research">Science/Research</option>
<option value="Telecommunications">Telecommunications</option>
<option value="Transportation/Logistics">Transportation/Logistics</option>
<option value="Other">Other</option>
